return {
	[1] = {
		enemies = {
			{ name = "Slime", count = 5, delay = 1 },
			{ name = "BossSlime", count = 1, delay = 1 },
		},
	},

	[2] = {
		enemies = {
			{ name = "Slime", count = 8, delay = 0.8 },
		},
	},

	[3] = {
		enemies = {
			{ name = "Slime", count = 16, delay = 0.5 },
		},
	},

	[4] = {
		enemies = {
			{ name = "Slime", count = 16, delay = 0.5 },
		},
	},

	[5] = {
		enemies = {
			{ name = "Slime", count = 16, delay = 0.5 },
		},
	},
}
